"""add unique constraint for ticker_symbol and date

Revision ID: 9060deffe629
Revises: b409808592ae
Create Date: 2025-06-22 18:29:38.972748

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9060deffe629"
down_revision: Union[str, Sequence[str], None] = "b409808592ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("return_data") as batch_op:
        batch_op.create_unique_constraint(
            "unique_ticker_date", ["ticker_symbol", "date"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("return_data") as batch_op:
        batch_op.drop_constraint("unique_ticker_date", type_="unique")
    # ### end Alembic commands ###
