# Development Configuration
# Pragmatic settings for local development and testing

environment: "development"
log_level: "DEBUG"

database:
  url: "postgresql://trader:password@localhost:5432/trading_research_dev"
  echo: true
  pool_size: 3
  max_overflow: 5

model:
  # Small dataset for fast iteration with optimized parameters
  tickers: ["AAPL", "MSFT", "GOOG"]
  lookback_window: 30
  prediction_horizon: 1  # 1-day prediction horizon for fast development iteration
  target_features: 20
  model_size: "small"  # Use smallest model for fast development
  
  training_params:
    batch_size: 32
    epochs: 20  # Fewer epochs for quick testing
    learning_rate: 0.001
    patience: 5
    validation_split: 0.2
    monitor_metric: "val__directional_accuracy"  # Fixed: correct TensorFlow metric name (double underscore)
    early_stopping_mode: "max"

backtest:
  transaction_cost: 0.001
  training_window_days: 126  # 6 months for development
  rebalance_frequency_days: 5
  walk_forward_window_days: 15  # Shorter windows

api:
  host: "127.0.0.1"
  port: 8000
  reload: true
  log_level: "DEBUG"
  model_cache_size: 2