# Production Configuration
# Full-scale settings for live trading research

environment: "production"
log_level: "INFO"

database:
  url: "postgresql://trader:secure_password@localhost:5432/trading_research"
  echo: false
  pool_size: 10
  max_overflow: 20

model:
  # Full dataset with optimized parameters
  tickers: ["AAPL", "MSFT", "GOOG", "NVDA", "TSLA", "AMZN", "META"]
  lookback_window: 30
  prediction_horizon: 3  # 3-day prediction horizon (changed from daily to 3-day for less noise)
  target_features: 24
  model_size: "medium"  # Options: "small" (~500K-800K), "medium" (~1M-1.5M), "large" (~3M+)
  
  training_params:
    batch_size: 64
    epochs: 100
    learning_rate: 0.0005
    patience: 5  # Fixed: reduced from 15 for faster convergence
    validation_split: 0.2
    monitor_metric: "val__directional_accuracy"  # Fixed: correct TensorFlow metric name (double underscore)
    early_stopping_mode: "max"

backtest:
  transaction_cost: 0.001
  min_position_size: 0.01
  max_position_size: 0.10
  max_drawdown_limit: 0.15
  volatility_target: 0.12
  training_window_days: 252
  rebalance_frequency_days: 5
  walk_forward_window_days: 30

api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  log_level: "INFO"
  model_cache_size: 5
  prediction_timeout: 30